config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  max_paginates_per 10
  has_many :comments

  def previous
    Post.where("created_at < ?", self.created_at).first
  end
  def next
    Post.where("created_at > ?", self.created_at).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:destroy]
  def create
    @comment = @post.comments.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post), notice: 'Comment was added.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_url(@post), notice: 'Comment was removed.' }
      format.json { head :no_content }
      format.js 
    end
  end
  private
  def set_post
    @post = Post.find(params[:post_id])
  end
  def set_comment
    @comment = @post.comments.find(params[:id])
  end
  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  def index
    @posts = Post.order(:created_at).page(params[:page]).per(10)
  end
  def show
    @post = Post.find(params[:id])
    @prev = @post.previous
    @next = @post.next
    @new_comment = @post.comments.build
  end
  def new
    @post = Post.new
  end
  def edit
  end
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end
  private
  def set_post
    @post = Post.find(params[:id])
  end
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
-logger.info @comment
-logger.info comment
%div{class: "row comment comment-#{comment.id}"}
  .col-sm-3
    .smallcaps
      #{ comment.created_at.strftime("%b %d, %Y")}
  .col-sm-8
    = comment.body
  .col-sm-1
    = link_to "Delete", post_comment_path(@post,comment), remote: true, method: :delete, data: { confirm: 'Are you sure?' }, id: "remove-comment-#{comment.id}", class: "remove-comment"

app/views/comments/create.js.haml
$('#comments').prepend('#{j render("comment", comment: @comment) }');
$('#add-comment form').find("input[type=text], textarea").val("");
empty_message = $('#comments').find("span.empty-message");
empty_message.text("");

app/views/comments/destroy.js.haml
$(".comment-#{@comment.id}").remove();

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header.page-scroll
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "/"} Sample UJS/Ajax Comments App
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => "/"} Home
        %li
          %a{:href => "/posts/new"} New Post
        %li
          %a{:href => "https://github.com/trh/rails_ujs_comments_example_app"} GitHub
    / /.navbar-collapse
  / /.container
/ Page Header
/ Set your background image for this header on the line below.
%header.intro-header{:style => "background-image: url(#{asset_url('home-bg.jpg')})"}
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        .site-heading
          %h1=content_for?(:page_header) ? yield(:page_header) : "Comments On A Single Page"
          %hr.small/
          %span.subheading=content_for?(:page_info) ? yield(:page_info) : "A simple rails app to display ajax comments, using ujs on a single post page"
          

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

:javascript
  $('.notif').delay(10000).fadeOut('slow');

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Same Page Comments
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}/
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    = render '/layouts/header'
    .site-notices
      = render '/layouts/messages'
    .container
      = yield
    %hr/
    / Footer
    %footer
      .container
        .row
          .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
            %ul.list-inline.text-center
              %li
                %a{:href => "https://github.com/trh/rails_ujs_comments_example_app"}
                  %span.fa-stack.fa-lg
                    %i.fa.fa-circle.fa-stack-2x
                    %i.fa.fa-github.fa-stack-1x.fa-inverse
            %p.copyright.text-muted Copyright -- Well there no copyright because nobody on GitHub is a stingy bastard. 

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :body
    %br/
    = f.text_area :body
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing Post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
.row
  .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
    - @posts.each do |post|
      .post-preview
        = link_to post do
          %h2.post-title
            = post.title.titleize
          %h3.post-subtitle
            = truncate(post.body, length: 100, omission: "... Read More")
        %p.post-meta
          Posted by
          %a{:href => "#"} bunglify
          on
          = post.created_at.strftime("%e")
      %hr/
    / Pager
    = paginate @posts

app/views/posts/new.html.haml
%h1 New Post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
- content_for :page_header do
  = @post.title
- content_for :page_info do
  = link_to content_tag(:i,'',class: "fa fa-pencil"), edit_post_path(@post)
  = link_to content_tag(:i,'',class: "fa fa-list"), posts_path
%p
  = @post.body.capitalize

%br/
%ul.pagination
  %li= link_to('Newer', post_path(@prev)) unless @prev.nil?
  %li= link_to('Older', post_path(@next)) unless @next.nil?

%br
%h3 Comments
#add-comment
  = form_for [@post, @new_comment], remote: true do |f|
    .form-fields
      = f.text_area :body, class: "form-control"
    .form-actions
      = f.submit "Comment Now", class: "btn btn-primary"
#comments
  = @post.comments.count < 1 ? "<span class='empty-message'> No Comments for Post<\/span>".html_safe : ""
  - @post.comments.order(created_at: :desc).each do |comment|
    = render comment unless comment.new_record?